#!/bin/sh

declare -p > $HOME/.ssh/last_connection_env
echo "export DISPLAY='$DISPLAY'" > $HOME/.ssh/last_connection_init

# run xauth initialization, from sshd(8)
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
        echo add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
    else
        echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi
