#!/bin/bash
pn=`basename "$0"`

function link_file ()
{
    link="$1"
    target="$2"
    echo "linking   $link -> $target"
    ln -sf "$target" "$link"
}

function replace_file ()
{
    link="$1"
    target="$2"
    rm -f "$link"
    link_file "$link" "$target"
}


replace_all=0
for file in *; do
    link="$HOME/.$file"
    target="`pwd`/$file"
    
    if [[ $file == "$pn" || $file == README* ]] ; then
        continue
    fi
    
    if [[ ! -e $link ]] ; then
        link_file "$link" "$target"
    elif [[ -L $link && `readlink "$link"` == "$target" ]] ; then
        echo "identical $link"
    elif [[ $replace_all != 0 ]] ; then
        replace_file "$link" "$target"
    else
        read -p "overwrite $link? [ynaq] " response
        case $response in
            a*|A*)
                replace_all=1
                replace_file "$link" "$target"
                ;;
            y*|Y*)
                replace_file "$link" "$target"
                ;;
            q*|Q*)
                exit
                ;;
            *)
                echo "skipping  $link"
                ;;
        esac
    fi
done
