(defvar foo
    ;; name      256        8
    '((black    "#000000"  ("black"))
      (dkgray   "#262626"  ("black" . t))
      (gray     "#7f7f7f"  ("white"))
      (ltgray   "#dadada"  ("white"))
      (white    "#ffffff"  ("white" . t))
      (red      "#ff0000"  ("red" . t))
      (orange   "#ff5f00"  ("red"))
      (ltorange "#ffaf87"  ("yellow"))
      (yellow   "#ffd787"  ("yellow" . t))
      (green    "#00ff00"  ("green"))
      (ltgreen  "#87ff87"  ("green" . t))
      (dkcyan   "#00cdcd"  ("cyan"))
      (cyan     "#00ffff"  ("cyan"))
      (ltcyan   "#87ffd7"  ("cyan" . t))
      (dkblue   "#0000af"  ("blue"))
      (blue     "#87afff"  ("blue" . t))
      (ltblue   "#afd7ff"  ("blue" . t))
      (magenta  "#ff00ff"  ("magenta" . t))
      (violet   "#af87ff"  ("magenta"))
      )
  "")

;; (defun face-for-index (orig-spec index &optional bold-attr)
;;   (let ((spec (copy-sequence orig-spec)))
;;     (dolist (property '(:foreground :background))
;;       (let ((color-name (plist-get spec property)))
;;         (when color-name
;;           (plist-put spec property )
;;       )
;;     spec)

;; (defun create-facespec (name spec)
;;   `(,name ((((min-colors 256))
;;             ,(face-for-index spec 1))
;;            (((min-colors 16))
;;             ,(face-for-index spec 2))
;;            (((min-colors 8))
;;             ,(face-for-index spec 2 t)))))

(defun color-theme-wisniewski ()
  "Color theme by jwisniewski, created 2015-12-20.
Based on standard graphical Emacs colors, but snapped to 256-color palette so
it'll look the same in a terminal, plus a few changes for readability."
  (interactive)
  (let (;; grays
        (black    "#000000")
        (dkgray   "#262626")
        (gray     "#7f7f7f")
        (ltgray   "#dadada")
        (white    "#ffffff")
        ;; colors
        (red      "#ff0000")
        (orange   "#ff5f00")
        (ltorange "#ffaf87")
        (yellow   "#ffd787")
        (green    "#00ff00")
        (ltgreen  "#87ff87")
        (dkcyan   "#00cdcd")
        (cyan     "#00ffff")
        (ltcyan   "#87ffd7")
        (dkblue   "#0000af")
        (blue     "#87afff")
        (ltblue   "#afd7ff")
        (magenta  "#ff00ff")
        (violet   "#af87ff"))
    (color-theme-install
     `(color-theme-wisniewski
       ((foreground-color . ,ltgray)
        (background-color . ,black)
        (background-mode . dark)
        (cursor-color . ,white))
       ;; basics
       (default ((t (:foreground ,ltgray))))
       (cursor ((t (:background ,white))))
       (error ((t (:background ,dkgray :foreground ,red :weight bold))))
       (fringe ((t (:background ,dkgray))))
       (isearch ((t (:background ,green :foreground ,white))))
       (isearch-fail ((t (:inherit error))))
       (lazy-highlight ((t (:background ,magenta :foreground ,white))))
       (link ((t (:foreground ,cyan :underline t))))
       (link-visited ((t (:foreground ,violet :underline t))))
       (minibuffer-prompt ((t (:foreground ,cyan))))
       (mode-line ((t (:background ,ltgray :foreground ,black :box (:line-width -1 :style released-button)))))
       (mode-line-inactive ((t (:background ,dkgray :foreground ,gray :box (:line-width -1 :style released-button) :weight light))))
       (region ((t (:background ,dkblue :foreground nil))))
       (show-paren-match ((t (:background ,gray :foreground ,cyan :weight bold))))
       (show-paren-mismatch ((t (:background ,red :foreground ,white :weight bold))))
       (trailing-whitespace ((t (:background ,dkgray :foreground ,dkcyan))))
       ;; font lock
       (font-lock-builtin-face ((t (:foreground ,ltblue))))
       (font-lock-comment-delimiter-face ((t (:foreground ,red))))
       (font-lock-comment-face ((t (:foreground ,orange))))
       (font-lock-constant-face ((t (:foreground ,ltcyan))))
       (font-lock-doc-face ((t (:inherit font-lock-comment-face))))
       (font-lock-function-name-face ((t (:foreground ,blue))))
       (font-lock-keyword-face ((t (:foreground ,cyan))))
       (font-lock-negation-char-face ((t (:inherit font-lock-keyword-face))))
       (font-lock-preprocessor-face ((t (:foreground ,violet))))
       (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
       (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
       (font-lock-string-face ((t (:foreground ,ltorange))))
       (font-lock-type-face ((t (:foreground ,ltgreen))))
       (font-lock-variable-name-face ((t (:foreground ,yellow))))
       (font-lock-warning-face ((t (:inherit error))))))))

(add-to-list 'color-themes '(color-theme-wisniewski  "Wisniewski" "Jim Wisniewski <wisnij@gmail.com>"))
